export const englishTermReplacements = [
  ['Personalized AI', '個人最適化AI'],
  ['Governed Discovery Ecosystem', '統治された発見エコシステム'],
  ['Distribution Enabled', '分配有効'],
  ['Technical Requirements', '技術要件'],
  ['AI-assisted / Generated Music', 'AI支援・生成音楽'],
  ['Reasoned Result', '理由付き結果'],
  ['Immutable Change History', '変更不能な変更履歴'],
  ['Verifiable Credentials', '検証可能な資格証明'],
  ['High Cache Hit', '高いキャッシュヒット'],
  ['Relational DB', '関係データベース'],
  ['Search Index', '検索索引'],
  ['Merkle Commitments', 'マークルコミットメント'],
  ['Embedded / Smart Wallet', '組込み・スマートウォレット'],
  ['Business Metrics', '事業指標'],
  ['Expected Cost', '予想コスト'],
  ['Load Test', '負荷テスト'],
  ['Batch Recommendation', 'バッチ推薦'],
  ['Aggregated Data', '集約データ'],
  ['Creator-first Dashboard', '音楽クリエーター中心ダッシュボード'],
  ['Listening Hours', '聴取時間'],
  ['Distributed Cache', '分散キャッシュ'],
  ['Regional Edge', '地域エッジ'],
  ['Rights Graph', '権利グラフ'],
  ['Payment Provider', '決済事業者'],
  ['Distribution Provider', '分配事業者'],
  ['Underlying Legal Right', '裏付けとなる法的権利'],
  ['Applicable Regulation', '適用規制'],
  ['Crypto Asset', '暗号資産'],
  ['Financial Instruments Rules', '金融商品ルール'],
  ['Tax Treatment', '税務上の取扱い'],
  ['Selected Markets', '選定市場'],
  ['Sanctions / Risk Screening', '制裁・リスク審査'],
  ['Data Minimization', 'データ最小化'],
  ['Purpose Limitation', '目的限定'],
  ['Intellectual Property', '知的財産'],
  ['Brand / Trademark', 'ブランド・商標'],
  ['Open-source License', 'オープンソースライセンス'],
  ['Product / Market Verification', 'プロダクト・市場検証'],
  ['Recorded Music Market', '録音音楽市場'],
  ['Ad-supported Streaming', '広告型ストリーミング'],
  ['Royalty Pool', 'ロイヤルティプール'],
  ['Smart Contracts', 'スマートコントラクト'],
  ['Clearly Labeled Promotion', '明示されたプロモーション'],
  ['Understand Audience', 'オーディエンス理解'],
  ['Explainable Suggestions', '説明可能な提案'],
  ['Known Preference', '既知の選好'],
  ['Unexpected Discovery', '予期しない発見'],
  ['New Preference', '新しい選好'],
  ['Support History', '支援履歴'],
  ['Financial Speculation', '金融投機'],
  ['Actual Listening', '実際の聴取'],
  ['Discovery Sources', '発見元'],
  ['Discovery Quality', '発見の品質'],
  ['Meaningful Support', '意味のある支援'],
  ['AI-assisted / Generated Music', 'AI支援・生成音楽'],
  ['Spam / Abuse Detection', 'スパム・不正利用検知'],
  ['Needs Investigation', '調査が必要'],
  ['Urgent / Serious', '緊急・重大'],
  ['Current Rights State', '現在の権利状態'],
  ['Immutable Change History', '変更不能な変更履歴'],
  ['Secure Off-chain Storage', '安全なオフチェーンストレージ'],
  ['Rights Declaration', '権利申告'],
  ['Risk Assessment', 'リスク評価'],
  ['Technical Requirements', '技術要件'],
  ['Reasoned Result', '理由付き結果'],
  ['Creator Consent', '音楽クリエーター同意'],
  ['Territory / Date', '地域・日付'],
  ['Artist Name', 'アーティスト名'],
  ['Business Metrics', '事業指標'],
  ['Expected Traffic', '予想トラフィック'],
  ['Expected Cost', '予想コスト'],
  ['Real-time Signals', 'リアルタイムシグナル'],
  ['Aggregated Data', '集約データ'],
  ['Managed Database', 'マネージドデータベース'],
  ['Distributed Cache', '分散キャッシュ'],
  ['North America', '北米'],
  ['Regional Edge', '地域エッジ'],
  ['Equity Financing', '株式による資金調達'],
  ['Rights Graph', '権利グラフ'],
  ['Stored Balance', '預り残高'],
  ['Transferable Value', '移転可能な価値'],
  ['Security Token Offering', 'セキュリティトークン募集'],
  ['Underlying Legal Right', '裏付けとなる法的権利'],
  ['Legal Classification', '法的分類'],
  ['Regulated Financial Firm', '規制対象金融事業者'],
  ['Licensed / Regulated Partner', '許認可・規制対象パートナー'],
  ['Corporate Records', '法人記録'],
  ['Shareholders / Board', '株主・取締役会'],
  ['Cross-border', '国境を越える取引'],
  ['Accounting Assessment', '会計評価'],
  ['Tax Classification', '税務分類'],
  ['Withholding if applicable', '必要な場合の源泉徴収'],
  ['Withholding Logic', '源泉徴収ロジック'],
  ['Electronic Payment Instrument', '電子決済手段'],
  ['権利登録台帳 Is Not a 著作権認定機関', '権利登録台帳は著作権認定機関ではない'],
  ['オンチェーン / オフチェーン Separation', 'オンチェーン・オフチェーンの分離'],
  ['ZKP Is Not the 正本', 'ZKPは正本ではない'],
  ['Transparent ZK Strategy', '透明型ゼロ知識証明戦略'],
  ['証明 Does Not Replace 監査', '証明は監査を代替しない'],
  ['Single 証明 システム for Everything', 'すべてを単一証明システムで処理'],
  ['ZKP as 業務ロジック', '業務ロジックとしてのZKP'],
  ['SBT alone grants all streaming', 'SBTだけですべてのストリーミングを許可'],
  ['Query blockchain synchronously for every media request', 'メディア要求ごとにブロックチェーンを同期照会'],
  ['Store privileges permanently in token metadata', '特権をトークンメタデータへ恒久保存'],
  ['Give the SBT governance or revenue rights', 'SBTへガバナンス権または収益権を付与'],
  ['Multiple Wallets', '複数ウォレット'],
  ['Wallet Unlinking', 'ウォレット連携解除'],
  ['Identity Layers', 'アイデンティティレイヤー'],
  ['Privacy-preserving Credentials', 'プライバシー保護型資格証明'],
  ['Payment Authorization Is Not Identity', '決済認可はアイデンティティではない'],
  ['Smart Accounts / Account Abstraction', 'スマートアカウント・アカウント抽象化'],
  ['Device Binding', '端末への結付け'],
  ['Personal Information', '個人情報'],
  ['Identity Provider Independence', 'アイデンティティプロバイダーからの独立'],
  ['Account Roles', 'アカウント役割'],
  ['Identity / Rights Separation', 'アイデンティティ・権利の分離'],
  ['Identity / Economic Power Separation', 'アイデンティティ・経済権力の分離'],
  ['Account Deletion', 'アカウント削除'],
  ['Pseudonymous Participation', '仮名参加'],
  ['Regulatory Boundary', '規制境界'],
  ['Progressive Verification', '段階的検証'],
  ['MVP Registration Flow', 'MVP登録フロー'],
  ['MVP Subscription Flow', 'MVPサブスクリプションフロー'],
  ['Wallet-only Identity', 'ウォレットだけのアイデンティティ'],
  ['Traditional Account Only', '従来型アカウントのみ'],
  ['Mandatory KYC for Every User', '全ユーザへのKYC義務付け'],
  ['One Wallet for Every Role', 'すべての役割で一つのウォレット'],
  ['Token-based Governance Identity', 'トークン基準のガバナンス・アイデンティティ'],
  ['Authenticated Usage', '認証済み利用実績'],
  ['Valid Usage', '有効な利用実績'],
  ['Usage States', '利用実績状態'],
  ['No Client-as-Authority', 'クライアントを権威ある記録にしない'],
  ['Zero-Knowledge Direction', 'ゼロ知識技術の方向性'],
  ['Transparent ZK Consideration', '透明型ゼロ知識証明の検討'],
  ['Deterministic Aggregation', '決定論的集約'],
  ['Challenge Mechanism', '異議申立て機構'],
  ['AI Role', 'AIの役割'],
  ['Oracle Decentralization', 'オラクルの分散化'],
  ['Data Retention', 'データ保存期間'],
  ['Fully Trusted Central Oracle', '全面的に信頼する中央オラクル'],
  ['Client-only Reporting', 'クライアントだけによる報告'],
  ['Public User-level Usage Ledger', '公開されたユーザ単位の利用実績台帳'],
  ['AI-only Verification', 'AIだけによる検証'],
  ['Verified Usage Only', '検証済み利用実績のみ'],
  ['Usage Weight Is Not Necessarily Raw Play Count', '利用実績重みは生の再生回数とは限らない'],
  ['No Pay-to-Govern Distribution Advantage', '資金力によるガバナンス・分配上の優位を認めない'],
  ['Rights-Aware Distribution', '権利考慮型分配'],
  ['Disputed Rights', '紛争中の権利'],
  ['Deterministic Calculation', '決定論的計算'],
  ['Rounding / Residual Amounts', '丸め処理・残余額'],
  ['Fraud Resistance', '不正耐性'],
  ['Platform Revenue Separation', 'プラットフォーム収益の分離'],
  ['Token-weighted Creator Distribution', 'トークン保有量加重の音楽クリエーター分配'],
  ['Low Barrier', '低い参加障壁'],
  ['Explainable Review', '説明可能なレビュー'],
  ['Human Appeal', '人による異議申立て'],
  ['Distribution Enabled', '分配有効'],
  ['Resistance to Manipulation', '操作耐性'],
  ['Constitutional Alignment', '憲章適合性'],
  ['Discovery Mode', '発見モード'],
  ['Cold Start', 'コールドスタート'],
  ['Discovery Budget', '発見予算'],
  ['Serendipity', '偶然の発見'],
  ['Curator Reputation', 'キュレーター評価'],
  ['Community Playlist', 'コミュニティプレイリスト'],
  ['Pay-to-Play', '支払による露出獲得'],
  ['Echo Chamber', 'エコーチェンバー'],
  ['Discovery Algorithm', '発見アルゴリズム'],
  ['Pull Request', 'プルリクエスト'],
  ['Pull リクエスト', 'プルリクエスト'],
  ['Recorded Music Market', '録音音楽市場'],
  ['Ad-supported Streaming', '広告型ストリーミング'],
  ['Paid Subscription', '有料サブスクリプション'],
  ['Market Growth', '市場成長'],
  ['Royalty Pool', 'ロイヤルティプール'],
  ['Label / Distributor', 'レーベル・ディストリビューター'],
  ['Publisher / CMO', '音楽出版社・著作権管理団体'],
  ['Popular Artist', '人気アーティスト'],
  ['More Plays', '再生増加'],
  ['More Revenue', '収益増加'],
  ['More Exposure', '露出増加'],
  ['Content Addressing', 'コンテンツアドレス指定'],
  ['Access Control', 'アクセス制御'],
  ['Object Storage', 'オブジェクトストレージ'],
  ['Transcoding / Packaging', 'トランスコード・パッケージ化'],
  ['Track ID', '楽曲ID'],
  ['Organization Verification', '組織検証'],
  ['Usage Association', '利用実績関連付け'],
  ['Revenue Split', '収益分割'],
  ['Delivery Logs', '配信ログ'],
  ['Raw Usage Data', '生の利用実績データ'],
  ['ZK Circuit', 'ZK回路'],
  ['Public Statement', '公開ステートメント'],
  ['Taxes / Payment / Required Costs', '税金・決済・必要経費'],
  ['Customer Support', '顧客対応'],
  ['External Partners', '外部パートナー'],
  ['Operational Systems', '運用システム'],
  ['Event Bus', 'イベントバス'],
  ['Async Usage Processing', '非同期利用実績処理'],
  ['Conventional DSP', '従来型DSP'],
  ['Required Costs', '必要経費'],
  ['Raw Plays', '生の再生回数'],
  ['Fraud Filtering', '不正除外'],
  ['Usage Weight', '利用実績重み'],
  ['Subscription Share', 'サブスクリプション比率'],
  ['Economic Contribution', '経済的貢献'],
  ['Listening-based', '聴取実績連動'],
  ['Explicit Support', '明示的支援'],
  ['Creative Projects', '創作プロジェクト'],
  ['Corporate Profit', '会社利益'],
  ['Market-Centric Pro-Rata Model', '市場中心比例配分モデル'],
  ['Equal Distribution to All Creators', '全音楽クリエーターへの均等分配'],
  ['Algorithmic Merit Distribution', 'アルゴリズム評価分配'],
  ['Rights-Aware Distribution', '権利考慮型分配'],
  ['Anti-Concentration Principle', '集中抑制原則'],
  ['Rounding and Residual Amounts', '丸め処理と残余額'],
  ['Minimum Payout', '最低分配額'],
  ['Real-world イベント', '現実世界のイベント'],
  ['Return to コミュニティ', 'コミュニティへ復帰'],
  ['Two-House Approval', '両院承認'],
  ['Two-House レビュー', '両院レビュー'],
  ['Two-House Policy Governance', '両院によるポリシーガバナンス'],
  ['Privacy-preserving Eligibility', 'プライバシー保護型の適格性'],
  ['Deliberation Quality', '熟議の質'],
  ['Integrated Player', '統合プレーヤー'],
  ['Treasury Flow Transparency Read Model', '資金フロー透明性参照モデル'],
  ['Bicameral Quadratic Governance', '二院制・二次投票ガバナンス'],
  ['Fully オフチェーン プラットフォーム', '完全オフチェーン型プラットフォーム'],
  ['Custom ブロックチェーン', '独自ブロックチェーン'],
  ['マルチチェーン from Launch', '開始時からのマルチチェーン'],
  ['Store Everything オンチェーン', 'すべてをオンチェーンへ保存'],
  ['Right Tool for the Right レイヤー', '各レイヤーに適した技術'],
  ['ストリーミング First', 'ストリーミング優先'],
  ['検証可能 Money', '検証可能な資金'],
  ['権利 before 分配', '分配より権利を優先'],
  ['ガバナンス over 重大 Rules', '重要ルールをガバナンスで統治'],
  ['Sustainable プラットフォーム', '持続可能なプラットフォーム'],
  ['二次 Funding', '二次資金配分'],
  ['音楽クリエーター比率 Floor', '音楽クリエーター分配率の下限'],
  ['Security-sensitive Change', 'セキュリティ上重要な変更'],
  ['Progressive Decentralization', '段階的分散化'],
  ['Sybil Resistance', 'シビル耐性'],
  ['Emergency Authority', '緊急権限'],
  ['Representation Audit', '代表性監査'],
  ['Governance Health', 'ガバナンスの健全性'],
  ['Governance Attack', 'ガバナンス攻撃'],
  ['Governance Transparency', 'ガバナンスの透明性'],
  ['Advisory Sortition', '助言型抽選'],
  ['Ecosystem Charter', 'エコシステム憲章'],
  ['Protocol Decision Queue', 'プロトコル決定一覧'],
  ['Responsibility Boundary', '責任境界'],
  ['Acceptance Criteria', '受入基準'],
  ['Trade-offs', 'トレードオフ'],
  ['Browser Fixture', 'ブラウザ用フィクスチャ'],
  ['same-origin Manifest', '同一オリジンのマニフェスト'],
  ['Production Candidate Topology', '本番候補構成'],
  ['Development and Presentation Test Environment', '開発・プレゼン用テスト環境'],
  ['Resource and Cost Boundary', '資源・コスト境界'],
  ['Runtime Boundary', '実行時境界'],
  ['Track Identity and Catalog Mapping', '楽曲識別子とカタログ対応付け'],
  ['Subscription and Rights Read Model', 'サブスクリプション・権利参照モデル'],
  ['Public API Boundary', '公開API境界'],
  ['Follow-up Work', '後続作業'],
  ['Primary Use Cases', '主要ユースケース'],
  ['Proof System Abstraction', '証明システム抽象化'],
  ['Strategic Candidate', '戦略的候補'],
  ['Trusted Setup Policy', '信頼されたセットアップのポリシー'],
  ['Post-Quantum Strategy', '耐量子戦略'],
  ['Public Inputs', '公開入力'],
  ['Circuit / Program Versioning', '回路・プログラムのバージョン管理'],
  ['Recursive Proofs', '再帰証明'],
  ['Proof Generation Infrastructure', '証明生成インフラ'],
  ['Proof Does Not Replace Audit', '証明は監査を代替しない'],
  ['Failure Handling', '障害処理'],
  ['Single Proof System for Everything', 'すべてを単一証明システムで処理'],
  ['ZKP as Business Logic', '業務ロジックとしてのZKP'],
  ['Qualification and Issuance', '資格判定と発行'],
  ['Privilege Policy', '特権ポリシー'],
  ['Authentication and Wallet Linking', '認証・ウォレット連携'],
  ['Authorization Read Model', '認可参照モデル'],
  ['Playback Session Binding', '再生セッションへの結付け'],
  ['STO and Legal Boundary', 'STO・法務境界'],
  ['Privacy and User Control', 'プライバシー・ユーザ制御'],
  ['Supporter SBT and Privileges', 'サポーターSBTと特権'],
  ['Integrated Player Client', '統合プレーヤークライアント'],
  ['OSS Reuse', 'OSS再利用'],
  ['Implementation Sequence', '実装順序'],
  ['Account and Wallet Experience', 'アカウント・ウォレット体験'],
  ['Supporter and Community Experience', 'サポーター・コミュニティ体験'],
  ['Client State and Privacy', 'クライアント状態・プライバシー'],
  ['Testnet Demo Topology', 'テストネットデモ構成'],
  ['Governance Population', 'ガバナンス母集団'],
  ['One Person / One Eligibility Principle', '一人一資格の原則'],
  ['Eligible Set Commitment', '適格者集合コミットメント'],
  ['Public Randomness', '公開乱数'],
  ['Deterministic Sortition', '決定論的抽選'],
  ['Replacement Members', '補欠議員'],
  ['Operator-controlled Random Selection', '運用者が制御する無作為選出'],
  ['Election-only Representation', '選挙だけによる代表制'],
  ['Pure Direct Democracy', '純粋な直接民主制'],
  ['Fairness', '公平性'],
  ['Unpredictability', '予測不能性'],
  ['Non-manipulability', '操作不能性'],
  ['Reproducibility', '再現可能性'],
  ['Investigation / Fix', '調査・修正'],
  ['Temporary Economic Power', '一時的な経済力'],
  ['Supply-chain Attacker', 'サプライチェーン攻撃者'],
  ['Low-friction Authentication', '低負担な認証'],
  ['Strong Authentication', '強固な認証'],
  ['Operating Corporation', '運営株式会社'],
  ['Corporate Responsibility', '法人責任'],
  ['Ethereum Compatibility', 'Ethereum互換性'],
  ['Canonical Protocol State', '正規プロトコル状態'],
  ['Ethereum L1 Only', 'Ethereum L1のみ'],
  ['Fully Off-chain Platform', '完全オフチェーン型プラットフォーム'],
  ['Custom Blockchain', '独自ブロックチェーン'],
  ['Multi-chain from Launch', '開始時からのマルチチェーン'],
  ['Store Everything On-chain', 'すべてをオンチェーンへ保存'],
  ['Why L2', 'L2を採用する理由'],
  ['Related Documents', '関連文書'],
  ['Right Tool for the Right Layer', '各レイヤーに適した技術'],
  ['Streaming First', 'ストリーミング優先'],
  ['Verifiable Money', '検証可能な資金'],
  ['Rights before Distribution', '分配より権利を優先'],
  ['Governance over Critical Rules', '重要ルールをガバナンスで統治'],
  ['Progressive Decentralization', '段階的分散化'],
  ['Transparent Rules', '透明なルール'],
  ['Fair Opportunity', '公正な機会'],
  ['Rights First', '権利優先'],
  ['Sustainable Platform', '持続可能なプラットフォーム'],
  ['Governed Economics', '統治された経済'],
  ['Usage-based Pool', '利用実績連動プール'],
  ['Quadratic Funding', '二次資金配分'],
  ['Creator Share Floor', '音楽クリエーター分配率の下限'],
  ['House Membership', '議員資格'],
  ['Quadratic Voting Round', '二次投票ラウンド'],
  ['Bicameral Governor', '二院制ガバナー'],
  ['Timelock Controller', 'タイムロック制御コントラクト'],
  ['Emergency Guardian', '緊急時ガーディアン'],
  ['Pull Request', 'プルリクエスト'],
  ['GitHub Issue', 'GitHub課題'],
  ['Finalized Payment', '確定済み決済'],
  ['Finalized Usage Snapshot', '確定済み利用実績スナップショット'],
  ['Finalized Revenue Snapshot', '確定済み収益スナップショット'],
  ['Finalized Distribution Result', '確定済み分配結果'],
  ['Optional Active', '任意の有効な'],
  ['Authorized Playback Session', '認可済み再生セッション'],
  ['Delivery Evidence', '配信証跡'],
  ['Distribution Policy Version', '分配ポリシー版'],
  ['Settlement Instruction', '精算指示'],
  ['Canonical Contracts', '正規コントラクト'],
  ['Account and Wallet Mock', 'アカウント・ウォレットのモック'],
  ['Asset and Payment Mock', '資産・決済のモック'],
  ['Usage Pipeline Mock', '利用実績パイプラインのモック'],
  ['Distribution Engine', '分配エンジン'],
  ['Settlement Stub', '精算スタブ'],
  ['End-to-End Harness', 'エンドツーエンド試験基盤'],
  ['Security, Privacy and Operations', 'セキュリティ・プライバシー・運用'],
  ['Threat Actors', '脅威主体'],
  ['External Attacker', '外部攻撃者'],
  ['Malicious Creator', '悪意ある音楽クリエーター'],
  ['Malicious User', '悪意あるユーザ'],
  ['Authorized Request', '認可済みリクエスト'],
  ['Authorized Review', '認可済みレビュー'],
  ['Duplicate Check', '重複検査'],
  ['Load Balancer', '負荷分散器'],
  ['Immutable Record', '変更不能な記録'],
  ['Real-world Event', '現実世界のイベント'],
  ['False Input', '偽の入力'],
  ['Test Vectors', 'テストベクトル'],
  ['Version Hash', '版ハッシュ'],
  ['Approved Change', '承認済み変更'],
  ['Transfer Limits', '送金上限'],
  ['Daily Operations', '日常運用'],
  ['Periodic Distribution', '定期分配'],
  ['Vote Buying', '票の買収'],
  ['Delegate Capture', '代表者掌握'],
  ['One Attacker', '一人の攻撃者'],
  ['Many Voters', '多数の投票者'],
  ['Concentrated Power', '集中した権力'],
  ['Human-readable Proposal', '人間可読な提案'],
  ['Executable Calls', '実行可能な呼出し'],
  ['Critical Incident', '重大インシデント'],
  ['Limited Pause', '限定停止'],
  ['Container Images', 'コンテナイメージ'],
  ['Security Checks', 'セキュリティ検査'],
  ['Protected Main', '保護されたmain'],
  ['Reviewed Source', 'レビュー済みソース'],
  ['Deterministic Build', '決定論的ビルド'],
  ['Artifact Hash', '成果物ハッシュ'],
  ['Encrypted Storage', '暗号化ストレージ'],
  ['Pseudonymous ID', '仮名ID'],
  ['Primary Backup', '主バックアップ'],
  ['Independent Backup', '独立バックアップ'],
  ['Restore Test', '復元テスト'],
  ['Alert / Response', '警告・対応'],
  ['Technical Response', '技術対応'],
  ['Legal Response', '法務対応'],
  ['Financial Design', '財務設計'],
  ['Distributable Revenue', '分配可能収益'],
  ['Usage-based Allocation', '利用実績連動配分'],
  ['Support Allocation', '支援配分'],
  ['Audit Trail', '監査証跡'],
  ['Distribution Parameters', '分配パラメータ'],
  ['Independent Creator', '独立系音楽クリエーター'],
  ['Sound Recording', '原盤'],
  ['Composition', '楽曲'],
  ['Rights Management', '権利管理'],
  ['Accounting / Tax', '会計・税務'],
  ['Dispute Resolution', '紛争解決'],
  ['Bicameral Quadratic Governance for Contract Changes', 'コントラクト変更の二院制・二次投票ガバナンス'],
  ['Centralized Mutable Database Only', '中央集権型の変更可能データベースのみ'],
  ['Separation of Work and Recording', '著作物と原盤の分離'],
  ['Privacy-Preserving Verifiability Layer', 'プライバシー保護型の検証可能性レイヤー'],
  ['Relationship to Other ADRs', '他のADRとの関係'],
  ['Governance Eligible User', 'ガバナンス適格ユーザ'],
  ['Creator Distribution', '音楽クリエーター分配'],
  ['Alternatives Considered', '検討した代替案'],
  ['Security Considerations', 'セキュリティ上の考慮事項'],
  ['Follow-up Specifications', '後続仕様'],
  ['Account Abstraction', 'アカウント抽象化'],
  ['Source of Truth', '正本'],
  ['Source-derived Register', 'ソースから導出した登録簿'],
  ['Decision Baseline', '決定基準'],
  ['Decision boundaries', '決定境界'],
  ['Decision owner', '決定責任者'],
  ['Contract boundary', 'コントラクト境界'],
  ['Validation Gates', '検証ゲート'],
  ['Validation Gate', '検証ゲート'],
  ['Role of Blockchain', 'ブロックチェーンの役割'],
  ['Layered Architecture', 'レイヤー構成'],
  ['Selection Criteria', '選定基準'],
  ['Business Logic', '業務ロジック'],
  ['Asset Abstraction', '資産抽象化'],
  ['Data Availability', 'データ可用性'],
  ['Infrastructure Neutrality', 'インフラ中立性'],
  ['Copyright Authority', '著作権認定機関'],
  ['Rights Claims', '権利主張'],
  ['Rights Types', '権利種別'],
  ['Fractional Rights', '権利持分'],
  ['Distribution Instructions', '分配指示'],
  ['Versioning and History', 'バージョン管理と履歴'],
  ['Effective Time', '効力発生時点'],
  ['External Rights Management', '外部権利管理'],
  ['Owner Model', '所有者モデル'],
  ['Fully On-chain', '完全オンチェーン'],
  ['Immutable Rights State', '変更不能な権利状態'],
  ['Token-weighted voting', 'トークン保有量加重投票'],
  ['Token Voting', 'トークン投票'],
  ['Direct Democracy', '直接民主制'],
  ['Election-based Representation', '選挙代表制'],
  ['One-member one-vote only', '議員一人一票のみ'],
  ['Community-wide QV for every change', '全変更に対するコミュニティ全体の二次投票'],
  ['Off-chain result plus administrator execution', 'オフチェーン結果と管理者による実行'],
  ['Public Testnet', '公開テストネット'],
  ['Testnet Demo', 'テストネットデモ'],
  ['Early Supporter', '初期サポーター'],
  ['Smart Contract', 'スマートコントラクト'],
  ['Rights Registry', '権利登録台帳'],
  ['Usage Oracle', '利用実績オラクル'],
  ['Usage Verification', '利用実績検証'],
  ['Zero-Knowledge Proof', 'ゼロ知識証明'],
  ['Settlement Asset', '精算資産'],
  ['Growth Pool', '成長支援プール'],
  ['Rights Holder', '権利者'],
  ['Protocol Specification', 'プロトコル仕様'],
  ['Open Question', '未解決事項'],
  ['Threat Model', '脅威モデル'],
  ['Smart Account', 'スマートアカウント'],
  ['Gas Sponsorship', 'ガス代支援'],
  ['Voice Credit', '投票クレジット'],
  ['Execution Manifest', '実行マニフェスト'],
  ['Membership Snapshot', '議員資格スナップショット'],
  ['Code is Law', 'コードは法である'],
  ['Architecture Decision Records', 'アーキテクチャ意思決定記録'],
  ['Streaming Authorization', 'ストリーミング認可'],
  ['Vertical Slice', '最小縦断実装'],
  ['End-to-End', 'エンドツーエンド'],
  ['Work Packages', '作業パッケージ'],
  ['Stage Gates', '段階ゲート'],
  ['Test Matrix', 'テスト一覧'],
  ['Trust Boundary', '信頼境界'],
  ['Least Privilege', '最小権限'],
  ['Defense in Depth', '多層防御'],
  ['Separation of Duties', '職務分離'],
  ['Privacy by Design', 'プライバシー・バイ・デザイン'],
  ['Zero Trust', 'ゼロトラスト'],
  ['Personal Data Minimization', '個人データ最小化'],
  ['Disaster Recovery', '災害復旧'],
  ['Incident Response', 'インシデント対応'],
  ['Responsible Disclosure', '責任ある脆弱性開示'],
  ['Formal Verification', '形式検証'],
  ['Supply Chain', 'サプライチェーン'],
  ['Reproducible Build', '再現可能ビルド'],
  ['Sybil Attack', 'シビル攻撃'],
  ['Payout Address', '分配先アドレス'],
  ['Playback Fraud Detection', '不正再生検知'],
  ['Proof Program', '証明プログラム'],
  ['Key Rotation', '鍵ローテーション'],
  ['Multi-chain', 'マルチチェーン'],
  ['Chain-specific', 'チェーン固有'],
  ['Claim-based', '申請方式'],
  ['Chain Failure', 'チェーン障害'],
  ['Emergency Controls', '緊急制御'],
  ['Key Management', '鍵管理'],
  ['Whitepaper', 'ホワイトペーパー'],
  ['Governance', 'ガバナンス'],
  ['Protocol', 'プロトコル'],
  ['Platform', 'プラットフォーム'],
  ['Rights', '権利'],
  ['Wallet', 'ウォレット'],
  ['Usage', '利用実績'],
  ['Proof', '証明'],
  ['Distribution', '分配'],
  ['Subscription', 'サブスクリプション'],
  ['Account', 'アカウント'],
  ['Playback', '再生'],
  ['Security', 'セキュリティ'],
  ['Verification', '検証'],
  ['Gateway', 'ゲートウェイ'],
  ['Contract', 'コントラクト'],
  ['Registry', '登録台帳'],
  ['Community', 'コミュニティ'],
  ['Blockchain', 'ブロックチェーン'],
  ['Payment', '決済'],
  ['Model', 'モデル'],
  ['Identity', 'アイデンティティ'],
  ['Player', 'プレーヤー'],
  ['Phase', 'フェーズ'],
  ['Session', 'セッション'],
  ['Commitment', 'コミットメント'],
  ['Oracle', 'オラクル'],
  ['Policy', 'ポリシー'],
  ['Cost', 'コスト'],
  ['Supporter', 'サポーター'],
  ['Discovery', '発見'],
  ['Public', '公開'],
  ['Settlement', '精算'],
  ['Asset', '資産'],
  ['Layer', 'レイヤー'],
  ['Privacy', 'プライバシー'],
  ['Growth', '成長'],
  ['Early', '初期'],
  ['Specification', '仕様'],
  ['Client', 'クライアント'],
  ['Streaming', 'ストリーミング'],
  ['Decision', '決定'],
  ['Support', '支援'],
  ['Chain', 'チェーン'],
  ['Token', 'トークン'],
  ['Revenue', '収益'],
  ['State', '状態'],
  ['Review', 'レビュー'],
  ['Snapshot', 'スナップショット'],
  ['Code', 'コード'],
  ['Address', 'アドレス'],
  ['Verified', '検証済み'],
  ['Legal', '法務'],
  ['Source', 'ソース'],
  ['Testnet', 'テストネット'],
  ['Test', 'テスト'],
  ['Mock', 'モック'],
  ['Authorization', '認可'],
  ['Infrastructure', 'インフラ'],
  ['Evidence', '証跡'],
  ['Data', 'データ'],
  ['Gas', 'ガス'],
  ['Transaction', 'トランザクション'],
  ['Execution', '実行'],
  ['Invariant', '不変条件'],
  ['Audit', '監査'],
  ['Verifiable', '検証可能'],
  ['Status', '状態'],
  ['Timelock', 'タイムロック'],
  ['Relayer', 'リレイヤー'],
  ['Implementation', '実装'],
  ['Draft', '草案'],
  ['Treasury', '資金庫'],
  ['Network', 'ネットワーク'],
  ['Storage', 'ストレージ'],
  ['Profile', 'プロフィール'],
  ['Media', 'メディア'],
  ['Adapter', 'アダプター'],
  ['Active', '有効'],
  ['Eligibility', '適格性'],
  ['Fraud', '不正'],
  ['Content', 'コンテンツ'],
  ['Zero-Knowledge', 'ゼロ知識'],
  ['Plan', '計画'],
  ['Strategy', '戦略'],
  ['Stablecoin', 'ステーブルコイン'],
  ['Recovery', '復旧'],
  ['Proposal', '提案'],
  ['On-chain', 'オンチェーン'],
  ['Off-chain', 'オフチェーン'],
  ['Application', 'アプリケーション'],
  ['Quadratic', '二次'],
  ['Metadata', 'メタデータ'],
  ['Manifest', 'マニフェスト'],
  ['Intent', '意思'],
  ['Economic', '経済'],
  ['Upgrade', 'アップグレード'],
  ['Slice', '部分実装'],
  ['Result', '結果'],
  ['Prover', '証明者'],
  ['Period', '期間'],
  ['Key', '鍵'],
  ['Claim', '主張'],
  ['Architecture', 'アーキテクチャ'],
  ['Range', '範囲'],
  ['Open', '公開'],
  ['Link', '連携'],
  ['Rule', 'ルール'],
  ['Proposed', '提案'],
  ['Private', '非公開'],
  ['Commit', 'コミット'],
  ['Audio', '音声'],
  ['Work', '作業'],
  ['Music', '音楽'],
  ['Eligible', '適格'],
  ['Demo', 'デモ'],
  ['Vertical', '垂直'],
  ['Release', 'リリース'],
  ['Events', 'イベント'],
  ['Event', 'イベント'],
  ['Deployment', 'デプロイ'],
  ['Risk', 'リスク'],
  ['Request', 'リクエスト'],
  ['Operation', '運用'],
  ['Context', '背景'],
  ['Decision', '決定'],
  ['Consequences', '影響'],
  ['Positive', '利点'],
  ['Negative', '欠点'],
  ['Constraints', '制約'],
  ['Finality', 'ファイナリティ'],
  ['Observability', '可観測性'],
  ['Upgradeability', 'アップグレード可能性'],
  ['Auditability', '監査可能性'],
  ['Disputes', '紛争'],
  ['Relationship', '関係'],
  ['Validation', '検証'],
  ['Monitoring', '監視'],
  ['Encryption', '暗号化'],
  ['Backup', 'バックアップ'],
  ['Internal', '内部'],
  ['Confidential', '機密'],
  ['Highly Sensitive', '極秘'],
  ['Verifiability', '検証可能性'],
  ['Recoverability', '復旧可能性'],
  ['Process', '手続'],
  ['Vision', 'ビジョン'],
  ['Discussion', '議論'],
  ['Deliberation', '熟議'],
  ['Automatic', '自動'],
  ['Tests', 'テスト'],
  ['Membership', '議員資格'],
  ['Voting', '投票'],
  ['Vote', '投票'],
  ['Round', 'ラウンド'],
  ['Controller', '制御コントラクト'],
  ['Proxy', 'プロキシ'],
  ['Guardian', 'ガーディアン'],
  ['Lifecycle', 'ライフサイクル'],
  ['Linking', '連携'],
  ['Credential', '資格証明'],
  ['Change', '変更'],
  ['Quorum', '定足数'],
  ['Deadlock', '膠着'],
  ['Finalized', '確定済み'],
  ['Optional', '任意'],
  ['Recording', '原盤'],
  ['Authorized', '認可済み'],
  ['Delivery', '配信'],
  ['Instruction', '指示'],
  ['Version', '版'],
  ['Purpose', '目的'],
  ['Challenge', '異議申立て'],
  ['Entry', '登録項目'],
  ['Native', 'ネイティブ'],
  ['Reference', '参照'],
  ['Entitlement', '利用権'],
  ['Catalog', 'カタログ'],
  ['Allocation', '配分'],
  ['Accounting', '会計'],
  ['Evolution', '進化'],
  ['Feature Branch', '機能ブランチ'],
  ['Build', 'ビルド'],
  ['Lint', '静的検査'],
  ['Human', '人間'],
  ['Signature', '署名'],
  ['Sortition', '抽選'],
  ['Local', 'ローカル'],
  ['Independent', '独立'],
  ['Production', '本番'],
  ['Journey', '利用フロー'],
  ['Indexer', 'インデクサー'],
  ['Authenticator', '認証器'],
  ['Ingest', '取込み'],
  ['Read Model', '参照モデル'],
  ['Record', '記録'],
  ['Notice', '通知'],
  ['Slot', 'スロット'],
  ['Canonical', '正規'],
  ['Distributable', '分配可能'],
  ['Operations', '運用'],
  ['Emerging', '新人'],
  ['Paymaster', 'ペイマスター'],
  ['Sustainability', '持続可能性'],
  ['Parameters', 'パラメータ'],
  ['Listeners', 'ユーザ'],
  ['Listener', 'ユーザ'],
  ['Pools', 'プール'],
  ['Contracts', '契約'],
  ['Transparent', '透明'],
  ['Personal', '個人'],
  ['Funds', '資金'],
  ['Bot', 'ボット'],
  ['Operator', '運用者'],
  ['Insider', '内部者'],
  ['Malicious', '悪意ある'],
  ['Attacker', '攻撃者'],
  ['Edge', 'エッジ'],
  ['Authentication', '認証'],
  ['Strong', '強固な'],
  ['Payout', '分配'],
  ['Upload', 'アップロード'],
  ['Notification', '通知'],
  ['Activation', '有効化'],
  ['Protected', '保護済み'],
  ['Read-only', '読取専用'],
  ['Service', 'サービス'],
  ['Services', 'サービス'],
  ['Internet', 'インターネット'],
  ['Farm', 'ファーム'],
  ['Automation', '自動化'],
  ['Fake', '偽造'],
  ['Illicit', '不正な'],
  ['Manipulation', '操作'],
  ['Detection', '検知'],
  ['Action', '対応'],
  ['Aggregation', '集約'],
  ['Input', '入力'],
  ['False', '偽の'],
  ['Trace', 'トレース'],
  ['Verifier', '検証者'],
  ['Vectors', 'ベクトル'],
  ['Compromised', '侵害された'],
  ['Invalid', '無効'],
  ['Reject', '拒否'],
  ['Fuzz', 'ファズ'],
  ['Deploy', 'デプロイ'],
  ['Executor', '実行者'],
  ['New', '新規'],
  ['Multisig', 'マルチシグ'],
  ['Hot', 'ホット'],
  ['Warm', 'ウォーム'],
  ['Cold', 'コールド'],
  ['Reserve', '予備'],
  ['Critical', '重大'],
  ['Access', 'アクセス'],
  ['Takeover', '乗っ取り'],
  ['Delegate', '代表者'],
  ['Temporary', '一時的'],
  ['Power', '権力'],
  ['Votes', '投票'],
  ['Hash', 'ハッシュ'],
  ['Pause', '停止'],
  ['Resume', '再開'],
  ['Packages', 'パッケージ'],
  ['Developer', '開発者'],
  ['Artifact', '成果物'],
  ['System', 'システム'],
  ['Cloud', 'クラウド'],
  ['Alert', '警告'],
  ['Response', '対応'],
  ['Detect', '検知'],
  ['Triage', '初動評価'],
  ['Contain', '封じ込め'],
  ['Eradicate', '根絶'],
  ['Recover', '復旧'],
  ['Postmortem', '事後検証'],
  ['Communication', '通知'],
  ['Bug', 'バグ'],
  ['Invariants', '不変条件'],
  ['Reentrancy', '再入'],
  ['Delegation', '委任'],
  ['Emergency', '緊急'],
  ['Incident', 'インシデント'],
  ['Referendum', '全体投票'],
  ['Compensation', '報酬'],
  ['Representation', '代表性'],
  ['Health', '健全性'],
  ['Attack', '攻撃'],
  ['Transparency', '透明性'],
  ['Agent', 'エージェント'],
  ['Advisory', '助言型'],
  ['Abstraction', '抽象化'],
  ['Corporation', '株式会社'],
  ['Admin', '管理'],
  ['Boundary', '境界'],
  ['Scope', '範囲'],
  ['Anchoring', 'アンカー記録'],
  ['Integration', '連携'],
  ['Sequencer', 'シーケンサー'],
  ['Bridge', 'ブリッジ'],
  ['Queue', '一覧'],
  ['Terminal', 'ターミナル'],
  ['Funding', '資金配分'],
  ['Score', 'スコア'],
  ['Reputation', '評価'],
  ['Pool', 'プール'],
  ['Floor', '下限'],
  ['Domains', '領域'],
  ['Format', '形式'],
  ['Conventions', '規約'],
  ['Glossary', '用語集'],
  ['Global Invariants', '全体不変条件'],
  ['Specs', '仕様'],
  ['Pipeline', 'パイプライン'],
  ['Engine', 'エンジン'],
  ['Stub', 'スタブ'],
  ['Harness', '試験基盤'],
  ['Privileges', '特権'],
  ['Privilege', '特権'],
  ['Standard', '標準'],
  ['Qualification', '資格判定'],
  ['Issuance', '発行'],
  ['Binding', '結付け'],
  ['Topology', '構成'],
  ['Environment', '環境'],
  ['Resource', '資源'],
  ['Runtime', '実行時'],
  ['Mapping', '対応付け'],
  ['Questions', '事項'],
  ['Question', '事項'],
  ['Development', '開発'],
  ['Presentation', 'プレゼン'],
  ['Candidate', '候補'],
  ['Server', 'サーバー'],
  ['Library', 'ライブラリ'],
  ['Flow', 'フロー'],
  ['Preview', 'プレビュー'],
  ['Gate', 'ゲート'],
  ['Payee', '受取人'],
  ['Pilot', '試行'],
  ['Scale', '規模拡大'],
  ['International Expansion', '国際展開'],
  ['Global', '国際'],
  ['Roadmap', 'ロードマップ'],
  ['Foundation', '基盤'],
  ['Consultation', '協議'],
  ['Auditable Ledger', '監査可能な台帳'],
  ['Repository', 'リポジトリ'],
  ['Versioning', 'バージョン管理'],
  ['Living Document', '継続更新文書'],
  ['North Star', '最重要指標'],
  ['Kill / Pivot Criteria', '中止・方向転換基準'],
  ['Integrity', '完全性'],
  ['Compliance', '法令遵守'],
  ['Identifiers', '識別子'],
  ['Track', '楽曲'],
  ['Master', '原盤'],
  ['Split', '分割'],
  ['App', 'アプリ'],
  ['Rules', 'ルール'],
  ['Dispute', '紛争'],
  ['Musical Work', '音楽著作物'],
  ['Lyrics', '歌詞'],
  ['Performance', '実演'],
  ['Contractual Rules', '契約ルール'],
  ['Database', 'データベース'],
  ['Anchor', 'アンカー'],
  ['Two Houses', '二院'],
  ['Members', '議員'],
  ['Fixed Term', '固定任期'],
  ['Return to Community', 'コミュニティへ復帰'],
  ['Randomness', '乱数'],
  ['Selection Algorithm', '選出アルゴリズム'],
  ['Selected Members', '選出議員'],
  ['Stakeholder Hearing', '利害関係者ヒアリング'],
  ['Simulation', 'シミュレーション'],
  ['Joint Approval', '共同承認'],
  ['Rejected / Rework', '否決・再作業'],
  ['Three Charters', '三憲章'],
  ['Charter Amendment', '憲章改正'],
  ['Constitutional Approval', '憲章適合承認'],
  ['Capital', '資本'],
  ['Business Responsibility', '事業責任'],
  ['Reasoned Return', '理由付き差戻し'],
  ['Re-deliberation', '再熟議'],
  ['Disclosure', '開示'],
  ['Personhood', '一人性'],
  ['Diversity', '多様性'],
  ['Safety', '安全性'],
  ['Trust', '信頼'],
  ['Operational', '運用事項'],
  ['Charter', '憲章'],
  ['Fast', '迅速'],
  ['Deliberative', '熟議型'],
  ['Supermajority', '特別多数'],
  ['Applicable Law', '適用法令'],
  ['Constitution', '憲章'],
  ['Joint', '共同'],
  ['Constitutional', '憲章適合'],
  ['and', '・'],
  ['Read', '参照'],
  ['Integrated', '統合'],
  ['Experience', '体験'],
  ['Sequence', '順序'],
  ['Web', 'ウェブ'],
  ['Mobile', 'モバイル'],
  ['Fork', 'フォーク'],
  ['Interaction', '連携'],
  ['Approved', '承認済み'],
  ['Assumption', '仮定'],
  ['Package', 'パッケージ'],
  ['Issue Form', '課題フォーム'],
  ['Issue', '課題'],
  ['Register', '登録簿'],
  ['Programs', 'プログラム'],
  ['Applications', 'アプリケーション'],
  ['Baseline', '基準'],
  ['Hardening', '強化'],
  ['Audits', '監査'],
  ['Program', '計画'],
  ['Centralized', '中央集権'],
  ['Shared Control', '共同管理'],
  ['Decentralized', '分散化'],
  ['Fair Ecosystem', '公正なエコシステム'],
  ['Prevent', '防止'],
  ['Limit', '制限'],
  ['Verify', '検証'],
  ['Periodic', '定期的'],
  ['Rotation', 'ローテーション'],
  ['Sybil', 'シビル'],
  ['Human-readable', '人間可読'],
  ['Checks', '検査'],
  ['Reviewed', 'レビュー済み'],
  ['Encrypted', '暗号化'],
  ['Primary', '主'],
  ['Restore', '復元'],
  ['Merkle Root', 'マークルルート'],
  ['File', 'ファイル'],
  ['Host Port', 'ホストポート'],
  ['External', '外部'],
  ['Free Tier', '無料枠'],
  ['Pricing', '料金'],
  ['Recommendation', '推薦'],
  ['Corporate', '法人'],
  ['Object', 'オブジェクト'],
  ['More', '増加'],
  ['Artist', 'アーティスト'],
  ['Songwriter', '作詞・作曲者'],
  ['Tax', '税務'],
  ['Metrics', '指標'],
  ['Listening', '聴取'],
  ['Analytics', '分析'],
  ['Required', '必要'],
  ['Check', '検査'],
  ['Economy', '経済'],
  ['Search', '検索'],
  ['Plays', '再生回数'],
  ['Costs', 'コスト'],
  ['Tier', '階層'],
  ['Store', '保存'],
  ['Simple', '単純'],
  ['Signals', 'シグナル'],
  ['Share', '比率'],
  ['Regulation', '規制'],
  ['Polynomial', '多項式'],
  ['Organization', '組織'],
  ['Management', '管理'],
  ['Level', 'レベル'],
  ['Investors', '投資家'],
  ['Investor', '投資家'],
  ['Initial', '初期'],
  ['Financial', '財務'],
  ['Creative', '創作'],
  ['Contribution', '貢献'],
  ['Cache', 'キャッシュ'],
  ['Autonomy', '自律性'],
  ['Physical', '物理媒体'],
  ['Digital', 'デジタル'],
  ['Download', 'ダウンロード'],
  ['Other', 'その他'],
  ['Label', 'レーベル'],
  ['Publisher', '音楽出版社'],
  ['Algorithm', 'アルゴリズム'],
  ['Creation', '創作'],
  ['Structure', '構造'],
  ['Generation', '世代'],
  ['Ownership', '所有'],
  ['Participation', '参加'],
  ['Addressing', 'アドレス指定'],
  ['Control', '制御'],
  ['Integrity', '完全性'],
  ['Manifests', 'マニフェスト'],
  ['Logs', 'ログ'],
  ['Raw', '生の'],
  ['Statement', 'ステートメント'],
  ['Taxes', '税金'],
  ['Customer', '顧客'],
  ['Partners', 'パートナー'],
  ['Clients', 'クライアント'],
  ['Update', '更新'],
  ['Notifications', '通知'],
  ['Async', '非同期'],
  ['Processing', '処理'],
  ['Requirements', '要件'],
  ['Scalability', '拡張性'],
  ['Ecosystem', 'エコシステム'],
  ['First', '優先'],
  ['Layers', 'レイヤー'],
  ['Only', 'のみ'],
  ['Weight', '重み'],
  ['Play Count', '再生回数'],
  ['Advantage', '優位'],
  ['Separation', '分離'],
  ['Resistance', '耐性'],
  ['Calculation', '計算'],
  ['Rounding', '丸め処理'],
  ['Residual Amounts', '残余額'],
  ['Minimum', '最低'],
  ['Pro-Rata', '比例配分'],
  ['Equal', '均等'],
  ['All', '全'],
  ['Algorithmic', 'アルゴリズム評価'],
  ['Merit', '評価'],
  ['Population', '母集団'],
  ['One Person / One', '一人一'],
  ['Principle', '原則'],
  ['Set', '集合'],
  ['Deterministic', '決定論的'],
  ['Pure', '純粋な'],
  ['Is Not a', 'はない'],
  ['Is Not', 'ではない'],
  ['Nullifiers', '無効化識別子'],
  ['Recurring', '継続'],
  ['Provider Independence', 'プロバイダーからの独立'],
  ['Revocation', '失効'],
  ['Roles', '役割'],
  ['Deletion', '削除'],
  ['Pseudonymous', '仮名'],
  ['Regulatory', '規制上の'],
  ['Progressive', '段階的'],
  ['Registration', '登録'],
  ['Traditional', '従来型'],
  ['Mandatory', '必須'],
  ['Every', '全'],
  ['Authenticated', '認証済み'],
  ['Valid', '有効'],
  ['States', '状態'],
  ['Direction', '方向性'],
  ['Consideration', '検討'],
  ['Finalization', '確定'],
  ['Mechanism', '機構'],
  ['Decentralization', '分散化'],
  ['Availability', '可用性'],
  ['Retention', '保存期間'],
  ['Trusted', '信頼された'],
  ['Central', '中央'],
  ['Reporting', '報告'],
  ['Ledger', '台帳'],
  ['Rights-Aware', '権利考慮型'],
  ['Disputed', '紛争中'],
  ['Alignment', '適合性'],
  ['Mode', 'モード'],
  ['Start', '開始'],
  ['Budget', '予算'],
  ['Curator', 'キュレーター'],
  ['Playlist', 'プレイリスト'],
  ['Opportunity', '機会'],
  ['Balance', '均衡'],
  ['For You', 'あなた向け'],
  ['Explore', '探索'],
  ['Voices', '参加者'],
  ['Rising', '注目上昇中'],
  ['Picks', '推薦選出'],
  ['Scene', 'シーン'],
  ['Random', '無作為'],
  ['Preference', '選好'],
  ['Novelty', '新規性'],
  ['Freshness', '鮮度'],
  ['Popular', '人気'],
  ['Match', '一致度'],
  ['Features', '特徴量'],
  ['Tags', 'タグ'],
  ['Editorial', '編集者選定'],
  ['Known', '既知'],
  ['Adjacent', '隣接'],
  ['Unexpected', '予期しない'],
  ['Discovered', '発見済み'],
  ['History', '履歴'],
  ['Linked', '連携済み'],
  ['Bounded', '限定'],
  ['Fan', 'ファン'],
  ['Speculation', '投機'],
  ['Role', '役割'],
  ['Find', '発見'],
  ['Collection', 'コレクション'],
  ['Region', '地域'],
  ['City', '都市'],
  ['Actual', '実際の'],
  ['Organic', '自然な'],
  ['Follows', 'フォロー'],
  ['Controls', '制御'],
  ['Results', '結果'],
  ['Sources', '情報源'],
  ['Audience', 'オーディエンス'],
  ['Activity', '活動'],
  ['Followers', 'フォロワー'],
  ['Report', '報告'],
  ['Moderation', 'モデレーション'],
  ['Appeal', '異議申立て'],
  ['Suggestions', '提案'],
  ['Team', 'チーム'],
  ['Principles', '原則'],
  ['Quality', '品質'],
  ['Meaningful', '意味のある'],
  ['Personalization', '個人最適化'],
  ['Curators', 'キュレーター'],
  ['Listen', '聴取'],
  ['Discover', '発見'],
  ['Grow', '成長'],
  ['Culture', '文化'],
  ['Declaration', '申告'],
  ['Agreement', '契約'],
  ['Band / Group', 'バンド・グループ'],
  ['Composer', '作曲者'],
  ['Performer', '実演家'],
  ['Information', '情報'],
  ['Biography', '略歴'],
  ['Genre', 'ジャンル'],
  ['Releases', 'リリース'],
  ['Individual', '個人'],
  ['Assessment', '評価'],
  ['Low', '低'],
  ['Medium', '中'],
  ['High', '高'],
  ['Automated', '自動'],
  ['Additional', '追加'],
  ['Confirmation', '確認'],
  ['Entity', '主体'],
  ['Terms', '条件'],
  ['Consent', '同意'],
  ['Territory', '地域'],
  ['Date', '日付'],
  ['Yes', 'はい'],
  ['Publish', '公開'],
  ['Popularity', '人気度'],
  ['Validity', '有効性'],
  ['Spam', 'スパム'],
  ['Abuse', '不正利用'],
  ['Clearly', '明確に'],
  ['Measures', '措置'],
  ['Keep', '維持'],
  ['Remove', '削除'],
  ['Restrict', '制限'],
  ['Current', '現在'],
  ['Secure', '安全な'],
  ['Tracks', '楽曲'],
  ['Registered', '登録済み'],
  ['Assistance', '支援'],
  ['Hybrid', 'ハイブリッド'],
  ['Reliability', '信頼性'],
  ['Databases', 'データベース'],
  ['Stream', 'ストリーム'],
  ['Buffer', 'バッファ'],
  ['Decode', 'デコード'],
  ['Transcoding', 'トランスコード'],
  ['Volume', 'ボリューム'],
  ['Lossless', 'ロスレス'],
  ['Long-tail', 'ロングテール'],
  ['Origin', 'オリジン'],
  ['Ingestion', '取込み'],
  ['Validated', '検証済み'],
  ['seconds', '秒'],
  ['minutes', '分'],
  ['hours', '時間'],
  ['days', '日'],
  ['month', '月'],
  ['Auditable', '監査可能'],
  ['Scalable', '拡張可能'],
  ['Embedded', '組込み'],
  ['Jobs', 'ジョブ'],
  ['Zone', 'ゾーン'],
  ['Replicated', '複製'],
  ['Tracing', 'トレーシング'],
  ['Transfer', '転送'],
  ['Compute', 'コンピュート'],
  ['Margin', '利益幅'],
  ['Engineering', 'エンジニアリング'],
  ['Finance', '財務'],
  ['Product', 'プロダクト'],
  ['Anomaly', '異常'],
  ['Traffic', 'トラフィック'],
  ['Autoscaler', '自動スケーラー'],
  ['Bottleneck', 'ボトルネック'],
  ['Optimization', '最適化'],
  ['Retest', '再テスト'],
  ['Real-time', 'リアルタイム'],
  ['Archive', 'アーカイブ'],
  ['Delete', '削除'],
  ['Staging', 'ステージング'],
  ['Apply', '適用'],
  ['Good', '良好な'],
  ['Paid', '有料'],
  ['Rate', '率'],
  ['Threshold', 'しきい値'],
  ['Autoscaled', '自動スケール'],
  ['Managed', 'マネージド'],
  ['Europe', '欧州'],
  ['Function', '機能'],
  ['Partner', 'パートナー'],
  ['Measure', '測定'],
  ['Identify', '特定'],
  ['Optimize', '最適化'],
  ['Saving', '削減'],
  ['Efficiency', '効率'],
  ['Equity', '株式'],
  ['Copyright', '著作権'],
  ['Producer', '製作者'],
  ['Fee', '手数料'],
  ['Offering', '募集'],
  ['Underlying', '裏付け'],
  ['Classification', '分類'],
  ['Issuer', '発行者'],
  ['Regulated', '規制対象'],
  ['Firm', '事業者'],
  ['Licensed', '許認可済み'],
  ['Records', '記録'],
  ['Shareholder', '株主'],
  ['Shareholders', '株主'],
  ['Board', '取締役会'],
  ['Effect', '効果'],
  ['Responsibility', '責任'],
  ['Liability', '債務'],
  ['Payable', '未払金'],
  ['Gross', '総額'],
  ['Net', '純額'],
  ['Reconciliation', '照合'],
  ['Electronic', '電子'],
  ['Instrument', '手段'],
  ['Promotion', 'プロモーション'],
  ['Personalized', '個人最適化'],
  ['Governed', '統治された'],
  ['Follow', 'フォロー'],
  ['Enabled', '有効'],
  ['Name', '名称'],
  ['Technical', '技術'],
  ['Generated', '生成'],
  ['Reasoned', '理由付き'],
  ['Immutable', '変更不能'],
  ['Credentials', '資格証明'],
  ['APIs', 'API'],
  ['Hit', 'ヒット'],
  ['Auth', '認証'],
  ['Index', '索引'],
  ['seconds-minutes', '秒から分'],
  ['minutes-hours', '分から時間'],
  ['days-month', '日から月'],
  ['Root', 'ルート'],
  ['Smart', 'スマート'],
  ['Business', '事業'],
  ['Expected', '予想'],
  ['Load', '負荷'],
  ['Batch', 'バッチ'],
  ['Aggregated', '集約'],
  ['Dashboard', 'ダッシュボード'],
  ['Hours', '時間'],
  ['Distributed', '分散'],
  ['Japan', '日本'],
  ['Regional', '地域'],
  ['Provider', '事業者'],
  ['Right', '権利'],
  ['Applicable', '適用'],
  ['Crypto', '暗号資産'],
  ['Instruments', '商品'],
  ['Treatment', '取扱い'],
  ['Participant', '参加者'],
  ['Participants', '参加者'],
  ['Screening', '審査'],
  ['Minimization', '最小化'],
  ['Limitation', '限定'],
  ['Price', '価格'],
  ['Employee', '従業員'],
  ['Contractor', '業務委託者'],
  ['Contributor', '貢献者'],
  ['Director', '取締役'],
  ['Documentation', '文書'],
  ['Resolution', '解決'],
  ['Hold', '保留'],
  ['Law', '法令'],
  ['Updated', '更新済み'],
  ['Corp.', '株式会社'],
  ['Market', '市場'],
  ['Filtering', '除外'],
  ['Explicit', '明示的'],
  ['Project', 'プロジェクト'],
  ['Visibility', '可視性'],
  ['Direct', '直接'],
  ['Subscribers', '加入者'],
  ['Returns', 'リターン'],
  ['Elements', '要素'],
  ['Splits', '分割'],
  ['Create', '創作'],
  ['Reward', '報酬'],
  ['Again', '再び'],
  ['Recorded', '録音'],
  ['Ad-supported', '広告型'],
  ['Royalty', 'ロイヤルティ'],
].sort(([left], [right]) => right.length - left.length);

export const terminologyExceptions = [
  'Creator First Platform',
  'Navidrome',
  'Ethereum',
  'Sepolia',
  'JPYC',
  'MockJPYC',
  'SBT',
  'STO',
  'DAO',
  'ADR',
  'CFP',
  'API',
  'UI',
  'UX',
  'L1',
  'L2',
  'ZK',
  'STARK',
  'IPFS',
  'GitHub',
  'Codex',
  'MVP',
  'RPC',
  'CDN',
  'DRM',
  'DDoS',
  'CI/CD',
  'ETH',
];
